// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zmvfwryykphghhemwnpt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InptdmZ3cnl5a3BoZ2hoZW13bnB0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5ODg1OTgsImV4cCI6MjA1OTU2NDU5OH0.MYTpYhucBKQD1Jenbs0b8RkLDcFWaHJYAKiSBDQXxr8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);