// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dnihkpgvtrwpotnzbudn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRuaWhrcGd2dHJ3cG90bnpidWRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NDcwMjgsImV4cCI6MjA1OTUyMzAyOH0.cBJA3prWirLuWI7QLM3rrCNaXA-_YkPtXVcWFXYdKog";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);